"""
Camera Capture Page for CrowdWatch
Self-contained HTML page served to mobile devices for live camera streaming.
Works on HTTP by providing both getUserMedia (when available) and
a canvas-based periodic capture fallback.
"""


def get_camera_html(ws_url: str, device_id: str, token: str) -> str:
    """
    Return a self-contained HTML page that captures camera frames
    and streams them to the backend via WebSocket.
    """
    # We use string concatenation instead of f-strings for the JavaScript
    # to avoid escaping nightmares with curly braces.
    return (
        '<!DOCTYPE html>\n'
        '<html lang="en">\n'
        '<head>\n'
        '<meta charset="UTF-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">\n'
        '<title>CrowdWatch Camera</title>\n'
        '<style>\n'
        '* { margin: 0; padding: 0; box-sizing: border-box; }\n'
        'body {\n'
        "  font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;\n"
        '  background: #0c1220;\n'
        '  color: #e2e8f0;\n'
        '  min-height: 100vh;\n'
        '  min-height: 100dvh;\n'
        '  display: flex;\n'
        '  flex-direction: column;\n'
        '  overflow: hidden;\n'
        '}\n'
        '.header {\n'
        '  padding: 16px 20px;\n'
        '  display: flex;\n'
        '  align-items: center;\n'
        '  justify-content: space-between;\n'
        '  border-bottom: 1px solid rgba(255,255,255,0.06);\n'
        '  background: rgba(12,18,32,0.9);\n'
        '  backdrop-filter: blur(12px);\n'
        '  -webkit-backdrop-filter: blur(12px);\n'
        '}\n'
        '.brand {\n'
        '  font-size: 16px;\n'
        '  font-weight: 800;\n'
        '  letter-spacing: -0.02em;\n'
        '}\n'
        '.brand span { color: #5eead4; }\n'
        '.status {\n'
        '  display: flex;\n'
        '  align-items: center;\n'
        '  gap: 6px;\n'
        '  padding: 4px 12px;\n'
        '  border-radius: 999px;\n'
        '  font-size: 11px;\n'
        '  font-weight: 600;\n'
        '  text-transform: uppercase;\n'
        '  letter-spacing: 0.05em;\n'
        '}\n'
        '.status.connected {\n'
        '  background: rgba(52,211,153,0.15);\n'
        '  color: #34d399;\n'
        '  border: 1px solid rgba(52,211,153,0.2);\n'
        '}\n'
        '.status.connecting {\n'
        '  background: rgba(251,191,36,0.15);\n'
        '  color: #fbbf24;\n'
        '  border: 1px solid rgba(251,191,36,0.2);\n'
        '}\n'
        '.status.disconnected {\n'
        '  background: rgba(248,113,113,0.15);\n'
        '  color: #f87171;\n'
        '  border: 1px solid rgba(248,113,113,0.2);\n'
        '}\n'
        '.status-dot {\n'
        '  width: 6px;\n'
        '  height: 6px;\n'
        '  border-radius: 50%;\n'
        '  background: currentColor;\n'
        '}\n'
        '.status.connected .status-dot {\n'
        '  animation: pulse 2s ease-in-out infinite;\n'
        '}\n'
        '@keyframes pulse {\n'
        '  0%, 100% { opacity: 1; }\n'
        '  50% { opacity: 0.4; }\n'
        '}\n'
        '.video-container {\n'
        '  flex: 1;\n'
        '  display: flex;\n'
        '  align-items: center;\n'
        '  justify-content: center;\n'
        '  position: relative;\n'
        '  background: #080d18;\n'
        '}\n'
        'video {\n'
        '  width: 100%;\n'
        '  height: 100%;\n'
        '  object-fit: cover;\n'
        '}\n'
        'canvas { display: none; }\n'
        '.stats-bar {\n'
        '  padding: 12px 20px;\n'
        '  display: flex;\n'
        '  align-items: center;\n'
        '  justify-content: space-between;\n'
        '  border-top: 1px solid rgba(255,255,255,0.06);\n'
        '  background: rgba(12,18,32,0.9);\n'
        '  font-size: 12px;\n'
        '}\n'
        '.stat {\n'
        '  display: flex;\n'
        '  flex-direction: column;\n'
        '  align-items: center;\n'
        '  gap: 2px;\n'
        '}\n'
        '.stat-label {\n'
        '  font-size: 9px;\n'
        '  text-transform: uppercase;\n'
        '  letter-spacing: 0.08em;\n'
        '  color: rgba(255,255,255,0.35);\n'
        '  font-weight: 600;\n'
        '}\n'
        '.stat-value {\n'
        "  font-family: 'JetBrains Mono', monospace;\n"
        '  font-size: 14px;\n'
        '  font-weight: 700;\n'
        '  color: #5eead4;\n'
        '}\n'
        '.prompt-overlay {\n'
        '  position: absolute;\n'
        '  inset: 0;\n'
        '  display: flex;\n'
        '  flex-direction: column;\n'
        '  align-items: center;\n'
        '  justify-content: center;\n'
        '  background: rgba(12,18,32,0.95);\n'
        '  gap: 16px;\n'
        '  text-align: center;\n'
        '  padding: 24px;\n'
        '}\n'
        '.prompt-overlay h2 {\n'
        '  font-size: 18px;\n'
        '  font-weight: 700;\n'
        '}\n'
        '.prompt-overlay p {\n'
        '  font-size: 13px;\n'
        '  color: rgba(255,255,255,0.5);\n'
        '  max-width: 280px;\n'
        '  line-height: 1.5;\n'
        '}\n'
        '.btn {\n'
        '  padding: 12px 32px;\n'
        '  border-radius: 12px;\n'
        '  border: none;\n'
        '  font-size: 14px;\n'
        '  font-weight: 700;\n'
        '  cursor: pointer;\n'
        '  background: #5eead4;\n'
        '  color: #0c1220;\n'
        '  transition: transform 0.1s;\n'
        '  -webkit-tap-highlight-color: transparent;\n'
        '}\n'
        '.btn:active { transform: scale(0.97); }\n'
        '.msg { font-size: 12px; color: rgba(255,255,255,0.4); margin-top: 8px; }\n'
        '</style>\n'
        '</head>\n'
        '<body>\n'
        '  <div class="header">\n'
        '    <div class="brand">CROWD<span>WATCH</span></div>\n'
        '    <div id="status" class="status connecting">\n'
        '      <div class="status-dot"></div>\n'
        '      <span id="statusText">Waiting...</span>\n'
        '    </div>\n'
        '  </div>\n'
        '\n'
        '  <div class="video-container">\n'
        '    <video id="video" autoplay playsinline muted style="display:none;"></video>\n'
        '    <canvas id="canvas"></canvas>\n'
        '    <div id="promptOverlay" class="prompt-overlay">\n'
        '      <h2>CrowdWatch Camera</h2>\n'
        '      <p>Tap the button below to start streaming your camera to the monitoring system.</p>\n'
        '      <button class="btn" id="startBtn" onclick="init()">Start Camera</button>\n'
        '      <p class="msg" id="msgText"></p>\n'
        '    </div>\n'
        '  </div>\n'
        '\n'
        '  <div class="stats-bar">\n'
        '    <div class="stat">\n'
        '      <span class="stat-label">Frames</span>\n'
        '      <span class="stat-value" id="frameCount">0</span>\n'
        '    </div>\n'
        '    <div class="stat">\n'
        '      <span class="stat-label">FPS</span>\n'
        '      <span class="stat-value" id="fpsCount">0</span>\n'
        '    </div>\n'
        '    <div class="stat">\n'
        '      <span class="stat-label">Status</span>\n'
        '      <span class="stat-value" id="connStatus">—</span>\n'
        '    </div>\n'
        '  </div>\n'
        '\n'
        '<script>\n'
        'var WS_URL = "' + ws_url + '";\n'
        'var DEVICE_ID = "' + device_id + '";\n'
        'var TOKEN = "' + token + '";\n'
        'var TARGET_FPS = 10;\n'
        'var FRAME_INTERVAL = 1000 / TARGET_FPS;\n'
        'var JPEG_QUALITY = 0.55;\n'
        '\n'
        'var ws = null;\n'
        'var video = null;\n'
        'var canvas = null;\n'
        'var ctx = null;\n'
        'var streaming = false;\n'
        'var framesSent = 0;\n'
        'var fpsFrames = 0;\n'
        'var lastFpsTime = Date.now();\n'
        'var sendTimer = null;\n'
        '\n'
        'function setStatus(state, text) {\n'
        '  var el = document.getElementById("status");\n'
        '  var textEl = document.getElementById("statusText");\n'
        '  el.className = "status " + state;\n'
        '  textEl.textContent = text;\n'
        '  document.getElementById("connStatus").textContent = text;\n'
        '}\n'
        '\n'
        'function setMsg(text) {\n'
        '  document.getElementById("msgText").textContent = text;\n'
        '}\n'
        '\n'
        'function updateStats() {\n'
        '  document.getElementById("frameCount").textContent = framesSent;\n'
        '  var now = Date.now();\n'
        '  var elapsed = (now - lastFpsTime) / 1000;\n'
        '  if (elapsed >= 1) {\n'
        '    document.getElementById("fpsCount").textContent = Math.round(fpsFrames / elapsed);\n'
        '    fpsFrames = 0;\n'
        '    lastFpsTime = now;\n'
        '  }\n'
        '}\n'
        '\n'
        'function init() {\n'
        '  video = document.getElementById("video");\n'
        '  canvas = document.getElementById("canvas");\n'
        '  ctx = canvas.getContext("2d");\n'
        '  setMsg("Requesting camera access...");\n'
        '  startCamera();\n'
        '}\n'
        '\n'
        'function startCamera() {\n'
        '  if (!navigator.mediaDevices || !navigator.mediaDevices.getUserMedia) {\n'
        '    setMsg("Camera API not available. Try HTTPS or a different browser.");\n'
        '    return;\n'
        '  }\n'
        '  navigator.mediaDevices.getUserMedia({\n'
        '    video: { facingMode: { ideal: "environment" }, width: { ideal: 1280 }, height: { ideal: 720 } },\n'
        '    audio: false\n'
        '  }).then(function(stream) {\n'
        '    video.srcObject = stream;\n'
        '    video.style.display = "block";\n'
        '    video.play();\n'
        '    document.getElementById("promptOverlay").style.display = "none";\n'
        '    setTimeout(function() {\n'
        '      canvas.width = Math.min(video.videoWidth || 640, 1280);\n'
        '      canvas.height = Math.min(video.videoHeight || 480, 720);\n'
        '      connectWebSocket();\n'
        '    }, 800);\n'
        '  }).catch(function(err) {\n'
        '    console.error("Camera error:", err);\n'
        '    setMsg("Camera error: " + err.message + ". Make sure you allow camera access.");\n'
        '  });\n'
        '}\n'
        '\n'
        'function connectWebSocket() {\n'
        '  if (ws && ws.readyState === WebSocket.OPEN) return;\n'
        '  setStatus("connecting", "Connecting...");\n'
        '\n'
        '  try {\n'
        '    ws = new WebSocket(WS_URL);\n'
        '  } catch(e) {\n'
        '    setStatus("disconnected", "WS Error");\n'
        '    setMsg("Cannot connect: " + e.message);\n'
        '    return;\n'
        '  }\n'
        '\n'
        '  ws.onopen = function() {\n'
        '    setStatus("connected", "Streaming");\n'
        '    streaming = true;\n'
        '    var ua = navigator.userAgent;\n'
        '    var name = "External Camera";\n'
        '    if (ua.indexOf("iPhone") >= 0 || ua.indexOf("iPad") >= 0) name = "iPhone Camera";\n'
        '    else if (ua.indexOf("Android") >= 0) name = "Android Camera";\n'
        '    ws.send(JSON.stringify({ type: "auth", token: TOKEN, device_id: DEVICE_ID, name: name }));\n'
        '    startStreaming();\n'
        '  };\n'
        '\n'
        '  ws.onclose = function() {\n'
        '    streaming = false;\n'
        '    if (sendTimer) { clearInterval(sendTimer); sendTimer = null; }\n'
        '    setStatus("disconnected", "Disconnected");\n'
        '    setTimeout(connectWebSocket, 2000);\n'
        '  };\n'
        '\n'
        '  ws.onerror = function() {\n'
        '    streaming = false;\n'
        '    if (ws) ws.close();\n'
        '  };\n'
        '}\n'
        '\n'
        'function startStreaming() {\n'
        '  if (sendTimer) { clearInterval(sendTimer); sendTimer = null; }\n'
        '  sendTimer = setInterval(function() {\n'
        '    if (!streaming || !ws || ws.readyState !== WebSocket.OPEN) return;\n'
        '    if (!video || video.readyState < 2) return;\n'
        '    if (canvas.width === 0) {\n'
        '      canvas.width = Math.min(video.videoWidth || 640, 1280);\n'
        '      canvas.height = Math.min(video.videoHeight || 480, 720);\n'
        '    }\n'
        '    ctx.drawImage(video, 0, 0, canvas.width, canvas.height);\n'
        '    var dataUrl = canvas.toDataURL("image/jpeg", JPEG_QUALITY);\n'
        '    var base64Data = dataUrl.split(",")[1];\n'
        '    if (base64Data) {\n'
        '      ws.send(JSON.stringify({ type: "frame", frame: base64Data }));\n'
        '      framesSent++;\n'
        '      fpsFrames++;\n'
        '      updateStats();\n'
        '    }\n'
        '  }, FRAME_INTERVAL);\n'
        '}\n'
        '</script>\n'
        '</body>\n'
        '</html>\n'
    )
